name: Pull Request Deployment
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]

jobs:

  call-converge:
    uses: iconicompany/werfactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      registry: registry.gitlab.com
      context: testing
      environment: ${{ github.head_ref || github.ref_name }} 
      domain: ${{ github.head_ref || github.ref_name }}.${{ github.repository_owner }}.icncd.ru
