name: Production Deployment
on:
  push:
    tags: ['v*','!v*-*']
jobs:
  call-deployment:
    uses: iconicompany/werfactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      #registry: registry.gitlab.com/${{ github.repository }}
      registry: ghcr.io/${{ github.repository }}
      context: production
      env: production
      setenv: env.DOMAIN=iconicompany.ru
