name: Prerelease Deployment
on:
  push:
    tags: ['v*-*']
jobs:
  call-deployment:
    uses: iconicompany/werfactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      registry: registry.gitlab.com
      context: production
      environment: production-alpha
      setenv: env.DOMAIN=alpha.iconicompany.ru
