name: Production Deployment
on:
  push:
    tags: ['*']
jobs:
  call-deployment:
    uses: iconicompany/werfactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      registry: registry.gitlab.com
      context: production
      environment: production
      setenv: env.DOMAIN=iconicompany.ru
