apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.werf.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.werf.name }}
  template:
    metadata:
      annotations:
        autocert.step.sm/name: {{ $.Values.werf.name }}{{ $.Values.werf.env }}
      labels:
        app: {{ $.Values.werf.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        ports:
        - containerPort: 3000
        env:
        - name: WERF_ENV
          value: {{ $.Values.werf.env }}
        - name: WERF_NAME
          value: {{ $.Values.werf.name }}
        - name: DATABASE_URL
          value: "{{ $.Values.env.DATABASE_URL }}?sslmode=require&sslcert=/var/run/autocert.step.sm/root.crt&sslidentity=/var/run/autocert.step.sm/site.p12"
        - name: DOMAIN
          value: {{ $.Values.env.DOMAIN }}
        #{{- range $name, $value := .Values.env }}
        #- name: {{ $name }}
        #  value: {{ $value | quote }}
        #{{- end }}
        volumeMounts:
        - name: {{ $.Values.werf.name }}
          mountPath: /var/apps/{{ $.Values.werf.name }}
          subPath: var
        - name: secret-volume
          readOnly: true
          subPath: ".env"
          mountPath: "/app/.env"
      volumes:
      - name: {{ $.Values.werf.name }}
        persistentVolumeClaim:
          claimName: {{ $.Values.werf.name }}-pvc
      - name: secret-volume
        secret:
          secretName: {{ $.Values.werf.name }}-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.werf.name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ $.Values.werf.name }}-{{ $.Values.werf.env }}
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
{{ if eq .Release.Namespace "iconicactions-production" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iconicactions-production
annotations:
  "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/kube/iconicactions-production
    server: node01
{{end}}
{{ if eq .Release.Namespace "iconicactions-main" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iconicactions-testing
annotations:
  "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/kube/iconicactions-testing
    server: node01
{{end}}
