apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.werf.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.werf.name }}
  template:
    metadata:
      annotations:
        autocert.step.sm/name: {{ $.Values.werf.name }}
      labels:
        app: {{ $.Values.werf.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        ports:
        - containerPort: 3000
        env:
        - name: WERF_ENV
          value: {{ $.Values.werf.env }}
        - name: WERF_NAME
          value: {{ $.Values.werf.name }}
        - name: DATABASE_USER
          value: {{ $.Values.werf.name }}_{{ $.Values.werf.env }}
        {{- range $name, $value := .Values.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
