{{ if eq .Release.Namespace "iconicactions-production" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iconicactions-production
  namespace: ""
annotations:
  "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/kube/iconicactions-production
    server: node01
{{end}}
---
{{ if eq .Release.Namespace "iconicactions-main" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iconicactions-testing
  namespace: ""
annotations:
  "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/kube/iconicactions-testing
    server: node01
{{end}}
