apiVersion: v1
kind: PersistentVolume
metadata:
  name: iconicactions-production
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/kube
    server: node01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iconicactions-testing
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  #nfs:
  #  path: /srv/kube
  #  server: node01
