apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.werf.name }}-secret
data:
  .env: |
        {{ if contains "production" $.Values.werf.env  }}
        {{ werf_secret_file "env-production" | b64enc }}
        {{ end }}
        {{ if contains "testing" $.Values.werf.env }}
        {{ werf_secret_file "env-testing" | b64enc }}
        {{ end }}
