name: Werf Deployment
on:
    workflow_call:
      inputs:
        registry:
          description: Container registry, e.g. registry.gitlab.com.
          type: string
        context:
          description: Deployment kubernetes context (production, staging, testing, etc)
          type: string
        environment:
          description: Deployment environment (production, branch name, pull request number, etc)
          type: string
        domain:
          description: Hosting domain, e.g. example.com
          type: string
      secrets:
        REGISTRY_USERNAME:
        REGISTRY_PASSWORD:
        WERF_SECRET_KEY:
        KUBE_CONFIG:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME || '~~TOKENAUTH~~' }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Define environment vars
        run: |
          echo "WERF_KUBECONFIG_BASE64<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.KUBE_CONFIG }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "WERF_KUBE_CONTEXT=${{ inputs.context }}" >> $GITHUB_ENV
          echo "WERF_ENV=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "WERF_SET_DOMAIN=env.DOMAIN=${{ inputs.domain }}" >> $GITHUB_ENV
          echo "WERF_REPO=${{ inputs.registry }}/${{ github.repository }}" >> $GITHUB_ENV
          echo "WERF_SECRET_KEY=${{ secrets.WERF_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Werf converge
        if: ${{  github.event_name == 'push' || github.event_name == 'pull_request' && github.event.action != 'closed' && contains( github.event.pull_request.labels.*.name, 'review' ) }}
        run:
          werf converge

      - name: Werf dismiss
        if: ${{ github.event_name == 'pull_request' && (github.event.action == 'closed' || !contains( github.event.pull_request.labels.*.name, 'review' )) }}
        run:
          werf dismiss --with-namespace
