name: Staging Deployment
on:
  push:
    tags: ['v*-*']
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      WERF_ENV: staging
      DOMAIN: staging.iconicompany.ru
