name: Testing Deployment
on:
  push:
    branches: ["main"]
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      DOCKER_BUILDKIT: true
      WERF_ENV: testing
      WERF_NAMESPACE: cloudauto-{1}
      DOMAIN: ${{ github.repository_owner }}.icncd.ru
      DATABASE_URL: postgres://postgresql01.kube01.icncd.ru
