name: Testing Deployment
on:
  push:
    branches: ["main"]
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      DOCKER_BUILDKIT: true
      WERF_ENV: testing
      SETENV: env.DOMAIN=${{ github.head_ref || github.ref_name }}.${{ github.repository_owner }}.icncd.ru
