name: Testing Deployment
on:
  push:
    branches: ["main", "sandbox"]
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      DOCKER_BUILDKIT: true
      WERF_ENV: sandbox
      WERF_NAMESPACE: ${{github.event.repository.name}}-${{ github.head_ref || github.ref_name }}
      SETENV: env.DOMAIN=${{ github.head_ref || github.ref_name }}.${{ github.repository_owner }}.icncd.ru
