name: Testing Deployment
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      SETENV: env.DOMAIN=${{ github.head_ref || github.ref_name }}.${{ github.repository_owner }}.icncd.ru
      POSTGRES_IMAGE: postgres
