name: Production Deployment
on:
  push:
    tags: ['v*','!v*-*']
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  packages: write # This is required for package publish
jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      WERF_ENV: production
      DOMAIN: iconicompany.ru
